### ISSUE TITLE
six.moves.socketserver not working in python 2.7

### ISSUE THREAD

**Issue by apogre** [Parsely/streamparse#113]
```pytb
anish-imac:~ anish$ sparse
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 8, in <module>
    load_entry_point('streamparse==1.0.1', 'console_scripts', 'sparse')()
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 521, in load_entry_point
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2632, in load_entry_point
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2312, in load
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2318, in resolve
  File "/Library/Python/2.7/site-packages/streamparse/__init__.py", line 11, in <module>
    import streamparse.cmdln
  File "/Library/Python/2.7/site-packages/streamparse/cmdln.py", line 6, in <module>
    from .ext.invoke import (list_topologies, kill_topology, run_local_topology,
  File "/Library/Python/2.7/site-packages/streamparse/ext/invoke.py", line 24, in <module>
    from ..contextmanagers import ssh_tunnel
  File "/Library/Python/2.7/site-packages/streamparse/contextmanagers.py", line 8, in <module>
    from six.moves.socketserver import UDPServer, TCPServer
ImportError: No module named socketserver
```

**Comment by apogre** [comment]
Issue #32

**Comment by dan-blanchard** [comment]
Could you please run the following commands and tell us their output?

```bash
python --version
python -c 'import six; print(six.__version__)'
python -c 'import six.moves; print(dir(six.moves))'
```

**Comment by apogre** [comment]
python --version
Python 2.7.6
python -c 'import six; print(six.__version__)'
1.4.1
python -c 'import six.moves; print(dir(six.moves))'
['__doc__', '__name__']

**Comment by dan-blanchard** [comment]
Ah, it's a bug in the very old version of `six` you're using.  Please install six 1.5 or newer (the latest is 1.9).

**Comment by apogre** [comment]
pip search six
six                       - Python 2 and 3 compatibility utilities
  INSTALLED: 1.9.0 (latest)
but
python -c "import six; print six.__version__"
1.4.1
What is wrong here? Can't upgrade six!

**Comment by dan-blanchard** [comment]
I bet if you do `which python` and `which pip`, you'll find that they're in different places (and for different Python installations).  I would recommend just installing the [Anaconda](http://continuum.io/downloads) Python distro and using that, because that way you don't end up accidentally putting stuff in `/Library` that shouldn't be there.

**Comment by mjpieters** [comment]
Note that the default Python 2.7 setup on Mac OS X 10.10 includes `six` version 1.4.1. Users should use a virtualenv to work around that.

**Comment by eyildiz-ugoe** [comment]
This error is still there. 

```
python -c 'import six; print(six.__version__)'
1.12.0

```

`
ImportError: No module named configparser`

Quite annoying.
