### ISSUE TITLE
java.io.FileNotFoundException when running a topology

### ISSUE THREAD

**Issue by hellais** [Parsely/streamparse#140]
Hi when I run the topology implemented here: https://github.com/hellais/ooni-pipeline-ng

I get the following error:

```
java.io.FileNotFoundException: File '/hadoop/storm/supervisor/stormdist/report-2-1431479889/stormconf.ser' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1763) ~[commons-io-2.4.jar:2.4]
	at backtype.storm.config$read_supervisor_storm_conf.invoke(config.clj:214) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.daemon.worker$fn__5339$exec_fn__2680__auto____5340.invoke(worker.clj:382) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.AFn.applyToHelper(AFn.java:185) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__5339$mk_worker__5416.doInvoke(worker.clj:373) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:500) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
2015-05-13 12:56:11 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:322) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__5339$mk_worker__5416.doInvoke(worker.clj:373) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:500) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
```

It seems to continue running nonetheless and I do see the sprout and bolts emitting tuples, but I fear some data is getting lost is the process.

Any idea what may be causing this?

The storm user has write permissions to `/hadoop/storm/supervisor/stormdist/` and the file seems to be there.

**Comment by dan-blanchard** [comment]
This isn't a streamparse issue, but rather a Storm one ([STORM-130](https://issues.apache.org/jira/browse/STORM-130)).  It should be fixed in 0.9.4+.
