### ISSUE TITLE
InvalidClassException when using HDP

### ISSUE THREAD

**Issue by hellais** [Parsely/streamparse#141]
When running this topology: https://github.com/hellais/ooni-pipeline-ng

I get the following error:

```
2015-05-13 12:59:05 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.RuntimeException: java.io.InvalidClassException: backtype.storm.spout.ShellSpout; local class incompatible: stream classdesc serialVersionUID = 5303483274196591321, local class serialVersionUID = 2421937382718805016
	at backtype.storm.serialization.DefaultSerializationDelegate.deserialize(DefaultSerializationDelegate.java:56) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.utils.Utils.deserialize(Utils.java:95) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.utils.Utils.getSetComponentObject(Utils.java:234) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.daemon.task$get_task_object.invoke(task.clj:73) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.daemon.task$mk_task_data$fn__4691.invoke(task.clj:180) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.util$assoc_apply_self.invoke(util.clj:888) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.daemon.task$mk_task_data.invoke(task.clj:173) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.daemon.task$mk_task.invoke(task.clj:184) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.daemon.executor$mk_executor$fn__4886.invoke(executor.clj:328) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.core$map$fn__4207.invoke(core.clj:2485) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:60) ~[clojure-1.5.1.jar:na]
	at clojure.lang.RT.seq(RT.java:484) ~[clojure-1.5.1.jar:na]
	at clojure.core$seq.invoke(core.clj:133) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$fn__6026.invoke(protocols.clj:54) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13) ~[clojure-1.5.1.jar:na]
	at clojure.core$reduce.invoke(core.clj:6177) ~[clojure-1.5.1.jar:na]
	at clojure.core$into.invoke(core.clj:6229) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.executor$mk_executor.invoke(executor.clj:328) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at backtype.storm.daemon.worker$fn__5339$exec_fn__2680__auto__$reify__5341$iter__5346__5350$fn__5351.invoke(worker.clj:410) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:60) ~[clojure-1.5.1.jar:na]
	at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.next(LazySeq.java:92) ~[clojure-1.5.1.jar:na]
	at clojure.lang.RT.next(RT.java:598) ~[clojure-1.5.1.jar:na]
	at clojure.core$next.invoke(core.clj:64) ~[clojure-1.5.1.jar:na]
	at clojure.core$dorun.invoke(core.clj:2781) ~[clojure-1.5.1.jar:na]
	at clojure.core$doall.invoke(core.clj:2796) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__5339$exec_fn__2680__auto__$reify__5341.run(worker.clj:410) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_67]
	at javax.security.auth.Subject.doAs(Subject.java:415) ~[na:1.7.0_67]
	at backtype.storm.daemon.worker$fn__5339$exec_fn__2680__auto____5340.invoke(worker.clj:390) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.AFn.applyToHelper(AFn.java:185) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__5339$mk_worker__5416.doInvoke(worker.clj:373) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:500) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
Caused by: java.io.InvalidClassException: backtype.storm.spout.ShellSpout; local class incompatible: stream classdesc serialVersionUID = 5303483274196591321, local class serialVersionUID = 2421937382718805016
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:617) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_67]
	at backtype.storm.serialization.DefaultSerializationDelegate.deserialize(DefaultSerializationDelegate.java:52) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	... 41 common frames omitted
2015-05-13 12:59:05 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:322) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__5339$mk_worker__5416.doInvoke(worker.clj:373) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:500) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
```

As you can tell from the log I am running storm `0.9.3.2.2.4.2-2` (the one shipped by hdp 2.2) and I have adjusted my `project.clj` to say  `:dependencies  [[org.apache.storm/storm-core "0.9.3"]`.

Putting in there `0.9.3.2.2.4.2-2` or any minor version number triggers the error:

```
Routing Python logging to /home/ooni/ooni-pipeline-ng/logs.
Running lein command to run local cluster:
lein run -m streamparse.commands.run/-main topologies/report.clj -t 0 --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'streamparse.log.path="/home/ooni/ooni-pipeline-ng/logs"' --option 'streamparse.log.level="debug"'
Could not find artifact org.apache.storm:storm-core:jar:0.9.3.2.2.4.2-2 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.apache.storm:storm-core:jar:0.9.3.2.2.4.2-2 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
```

Any tips on how to debug or fix this?

**Comment by dan-blanchard** [comment]
I think the issue is that HortonWorks has their own versions of Storm that are separate from the official Apache ones.

You should just be able to add

```clj
:repositories {"HDP Releases" "http://repo.hortonworks.com/content/repositories/releases"}
```

to your `project.clj` and then set the Storm version to be exactly what they use.

**Comment by hellais** [comment]
Excellent. That fixed it.

I added documentation for this in the above PR.

**Comment by dan-blanchard** [comment]
Awesome.  Thanks for the PR! :+1:
