### ISSUE TITLE
Cannot run program "python"  error on sparse run

### ISSUE THREAD

**Issue by lboudard** [Parsely/streamparse#192]
Hi,

I'm trying to run basic examples 
wordcount quickstart
and
https://github.com/Parsely/streamparse/tree/master/examples/kafka-jvm)

Though I get the following error when trying to sparse run:

```bash
sparse run -d
```

> 4356 [Thread-13-count-bolt] ERROR backtype.storm.util - Async loop died!
> java.lang.RuntimeException: Error when launching multilang subprocess
>	at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:66) ~[storm-core-0.9.5.jar:0.9.5]
>	at backtype.storm.task.ShellBolt.prepare(ShellBolt.java:117) ~[storm-core-0.9.5.jar:0.9.5]
>	at backtype.storm.daemon.executor$fn__3439$fn__3451.invoke(executor.clj:692) ~[storm-core-0.9.5.jar:0.9.5]
>	at backtype.storm.util$async_loop$fn__460.invoke(util.clj:461) ~[storm-core-0.9.5.jar:0.9.5]
>	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
>	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
> Caused by: java.io.IOException: Cannot run program "python" (in directory "/tmp/2d571435-fd54-480f-9507-257e5e9e6874/supervisor/stormdist/wordcount-1-1444752484/resources"): error=2, Aucun fichier ou dossier de ce type
>	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_45]
>	at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:61) ~[storm-core-0.9.5.jar:0.9.5]
>	... 5 common frames omitted
> Caused by: java.io.IOException: error=2, Aucun fichier ou dossier de ce type
>	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.8.0_45]
>	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~[na:1.8.0_45]
>	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[na:1.8.0_45]
>	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_45]
>	... 6 common frames omitted

Do you have an idea on this issue? How exactly python is supposed to be called in run mode?

Thanks!

**Comment by lboudard** [comment]
I also had same kind of issue on submit on storm VM.

> java.lang.RuntimeException: Error when launching multilang subprocess at
backtype.storm.utils.ShellProcess.launch(ShellProcess.java:66) at  backtype.storm.task.ShellBolt.prepare(ShellBolt.java:117) at backtype.storm.daemon.executor$fn__4722$fn__4734.invoke(executor.clj:692) at backtype.storm.util$async_loop$fn__458.invoke(util.clj:461) at clojure.lang.AFn.run(AFn.java:24) at java.lang.Thread.run(Thread.java:745) Caused by: java.io.IOException: Cannot run program "/data/virtualenvs/recommendation/bin/python" (in directory "/home/storm/storm-data/supervisor/stormdist/recommendation-1-1444753780/resources"): error=2, No such file or directory at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:61) ... 5 more Caused by: java.io.IOException: error=2, No such file or directory at java.lang.UNIXProcess.forkAndExec(Native Method) at java.lang.UNIXProcess.<init>(UNIXProcess.java:186) at java.lang.ProcessImpl.start(ProcessImpl.java:130) at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028) ... 6 more

Which seems same as
https://mail-archives.apache.org/mod_mbox/storm-user/201406.mbox/%3CCAH9_-dnRCZi8aPAVtFmVVE6qME-7kHU6HX1BKaLE=w3WziLA_A@mail.gmail.com%3E

**Comment by lboudard** [comment]
Error came from leiningen version; I fixed that upgrading to 2.5.3.
