### ISSUE TITLE
Deploy remote: Required field 'nimbus_uptime_secs' is unset!

### ISSUE THREAD

**Issue by nicasio** [Parsely/streamparse#202]
Hello.

I'm using:
Mac OS for development.
streamparse: 2.1.3
In the server:
Storm: 0.10.0

He tried deploy the code:

```sh
$ sparse submit  -e prod --name ptp
```

```sh
Uber-JAR created: /Users/nicasio/primary/dataproccess/storm-py/pmy/_build/storm-pmy-0.0.1-SNAPSHOT-standalone.jar
Deploying "ptp" topology...
ssh tunnel to Nimbus 192.168.10.90:6627 established.
Routing Python logging to /home/nlino/logs/streamparse.
Running lein command to submit topology to nimbus:
lein run -m streamparse.commands.submit_topology/-main topologies/ptp.clj --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'topology.python.path="/data/virtualenvs/ptp/bin/pyth
on"' --option 'streamparse.log.path="/home/nlino/logs/streamparse"' --option 'streamparse.log.max_bytes=1000000' --option 'streamparse.log.backup_count=10' --option 'streamparse.log.level="debug"'
{:option {streamparse.log.level debug, streamparse.log.backup_count 10, streamparse.log.max_bytes 1000000, streamparse.log.path /home/nlino/logs/streamparse, topology.python.path /data/virtualenvs/ptp/bin
/python, topology.acker.executors 2, topology.workers 2}, :debug false, :port 6627, :host localhost, :help false}
Caught exception: org.apache.thrift7.protocol.TProtocolException: Required field 'nimbus_uptime_secs' is unset! Struct:ClusterSummary(supervisors:[SupervisorSummary(host:superhost, uptime_secs:78109, num_w
orkers:2, num_used_workers:0, supervisor_id:d00c750d-294f-462b-a057-cc9c59efc6f4)], nimbus_uptime_secs:0, topologies:[])

java.lang.RuntimeException: org.apache.thrift7.protocol.TProtocolException: Required field 'nimbus_uptime_secs' is unset! Struct:ClusterSummary(supervisors:[SupervisorSummary(host:superhost, uptime_secs:78
109, num_workers:2, num_used_workers:0, supervisor_id:d00c750d-294f-462b-a057-cc9c59efc6f4)], nimbus_uptime_secs:0, topologies:[])
 at backtype.storm.StormSubmitter.topologyNameExists (StormSubmitter.java:211)
    backtype.storm.StormSubmitter.submitTopology (StormSubmitter.java:117)
    backtype.storm.StormSubmitter.submitTopology (StormSubmitter.java:70)
    streamparse.commands.submit_topology$submit_topology_BANG_.invoke (submit_topology.clj:23)
    streamparse.commands.submit_topology$_main.doInvoke (submit_topology.clj:86)
    clojure.lang.RestFn.invoke (RestFn.java:1789)
    clojure.lang.Var.invoke (Var.java:483)
    user$eval5.invoke (form-init7674699633928198013.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6619)
    clojure.lang.Compiler.eval (Compiler.java:6609)
    clojure.lang.CException in thread "main" ompiler.load (Compiler.java:7064)
    clojure.lang.Compiler.loadFile (Compiler.java:7020)
    clojure.main$load_script.invoke (main.clj:294)
    clojure.main$init_opt.invoke (main.clj:299)
    clojure.main$initialize.invoke (main.clj:327)
    clojure.main$null_opt.invoke (main.clj:362)
    clojure.main$main.doInvoke (main.clj:440)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:419)
    clojure.lang.AFn.applyToHelper (AFn.java:163)
    clojure.lang.Var.applyTo (Var.java:532)
    clojure.main.main (main.java:37)
java.lang.NullPointerException
        at streamparse.commands.submit_topology$submit_topology_BANG_.invoke(submit_topology.clj:28)
        at streamparse.commands.submit_topology$_main.doInvoke(submit_topology.clj:86)
        at clojure.lang.RestFn.invoke(RestFn.java:1789)
```

config.json

```sh
{
    "library": "",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "nlino",
            "nimbus": "192.168.10.90:6627",
            "workers": [
              "192.168.10.90"
            ],
            "log": {
                "path": "/home/nlino/logs/streamparse",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "debug"
            },
            "virtualenv_root": "/data/virtualenvs"
        }
    }
}
```

project.clj
```sh
(defproject storm-pmy "0.0.1-SNAPSHOT"
  :source-paths ["topologies"]
  :resource-paths ["_resources"]
  :target-path "_build"
  :min-lein-version "2.0.0"
  :jvm-opts ["-client"]
  :dependencies  [[org.apache.storm/storm-core "0.9.5"]
                  [com.parsely/streamparse "0.0.4-SNAPSHOT"]
                  ]
  :jar-exclusions     [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  :uberjar-exclusions [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  )

```

Any idea?

**Comment by dan-blanchard** [comment]
Your storm version in `project.clj` needs to match version you're submitting the topology too.  In the next major release we'll be getting rid of the need to muck about with Clojure at all, so shouldn't be a longterm issue.  For now, just modify your `project.clj` to change `0.9.5` to `0.10.0`.

**Comment by nicasio** [comment]
Thanks for the reply.

I did the upgrada:
```sh
(venv)[17:16:08] nicasio:stale git:(master*) $ cat extract-native.dependencies
```
```sh
([:dependencies ([org.apache.storm/storm-core "0.10.0"] [com.parsely/streamparse "0.0.4-SNAPSHOT"] [org.clojure/tools.nrepl "0.2.10" :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete "0.2.3" :exclusions ([org.clojure/clojure])])])%
```

but the problem persist. I'm using Ambari to manager Storm.

I tested tar.gz version storm (v0.9.5), this work.

**Comment by lboudard** [comment]
Also encountering same issue there, though it seems a bug from hortonwork's storm version
https://issues.apache.org/jira/browse/STORM-1189

**Comment by dan-blanchard** [comment]
I'm going to close this issue, since it seems to be an upstream problem.
