### ISSUE TITLE
Can't run sparse (runaway version of `invoke`!)

### ISSUE THREAD

**Issue by sujaymansingh** [Parsely/streamparse#222]
```
$ python --version
Python 2.7.9

$ virtualenv /tmp/testing-sparse
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/testing-sparse/bin/python2
Also creating executable in /tmp/testing-sparse/bin/python
Installing setuptools, pip...done.

$ /tmp/testing-sparse/bin/pip install streamparse
Downloading/unpacking streamparse
  Using download cache from /opt/pip-cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fs%2Fstreamparse%2Fstreamparse-2.1.4.zip
  Running setup.py (path:/tmp/pip-build-w5dcGG/streamparse/setup.py) egg_info for package streamparse
    
<snip>

Successfully installed streamparse invoke fabric jinja2 requests prettytable six simplejson contextlib2 paramiko MarkupSafe ecdsa pycrypto
Cleaning up...

$ /tmp/testing-sparse/bin/sparse 
Traceback (most recent call last):
  File "/tmp/testing-sparse/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==2.1.4', 'console_scripts', 'sparse')()
  File "/tmp/testing-sparse/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 51, in main
    load_subparsers(subparsers)
  File "/tmp/testing-sparse/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 27, in load_subparsers
    module = importlib.import_module('streamparse.cli.{}'.format(mod_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/testing-sparse/local/lib/python2.7/site-packages/streamparse/cli/jar.py", line 9, in <module>
    from invoke import run
  File "/tmp/testing-sparse/local/lib/python2.7/site-packages/invoke/__init__.py", line 2, in <module>
    from .collection import Collection  # noqa
  File "/tmp/testing-sparse/local/lib/python2.7/site-packages/invoke/collection.py", line 7, in <module>
    from .config import merge_dicts
  File "/tmp/testing-sparse/local/lib/python2.7/site-packages/invoke/config.py", line 11, in <module>
    from .vendor import yaml2 as yaml
ImportError: cannot import name yaml2
```

**Comment by sujaymansingh** [comment]
I encountered the above issue on a project that was using `streamparse==2.0.2`, but it seems to be happening even with the latest version.

```
$ /tmp/testing-sparse/bin/pip freeze | grep stream
streamparse==2.1.4
```

**Comment by sujaymansingh** [comment]
I think it is an incompatibility with the latest version of `invoke`.

```
$ /tmp/testing-sparse/bin/pip freeze | grep invoke
invoke==0.12.1

$ /tmp/testing-sparse/bin/pip install invoke==0.11.1
Downloading/unpacking invoke==0.11.1
  Using download cache from /opt/pip-cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2.py3%2Fi%2Finvoke%2Finvoke-0.11.1-py2.py3-none-any.whl
Installing collected packages: invoke
  Found existing installation: invoke 0.12.1
    Uninstalling invoke:
      Successfully uninstalled invoke
Compiling /tmp/pip-build-KmeW6I/invoke/invoke/vendor/yaml3/__init__.py ...
  File "/tmp/pip-build-KmeW6I/invoke/invoke/vendor/yaml3/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax

Successfully installed invoke
Cleaning up...

$ /tmp/testing-sparse/bin/sparse                                                                                                                               
usage: sparse [-h] [--version]
              {jar,kill,list,quickstart,remove_logs,run,slot_usage,stats,submit,tail,update_virtualenv,visualize,worker_uptime}
              ...
sparse: error: too few arguments
```

**Comment by sujaymansingh** [comment]
Perhaps it would be worth pinning the requirements in `setup.py` ?

**Comment by dan-blanchard** [comment]
This has been fixed in invoke, so I'm closing this.  This was a weird fluke on their end where a bad tarball got uploaded, so I'm not going to pin versions over it.
