### ISSUE TITLE
Error while trying to submit topology

### ISSUE THREAD

**Issue by mlifemaker** [Parsely/streamparse#245]
Hey,
I'm trying to submit my topology to our storm cluster with:

sparse submit

but I'm getting this error:

```pytb
Deploying "feedcrmproduct" topology...
Traceback (most recent call last):
  File "/home/mohamed/Envs/feedcrm/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/home/mohamed/Envs/feedcrm/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 57, in main
    args.func(args)
  File "/home/mohamed/Envs/feedcrm/local/lib/python2.7/site-packages/streamparse/cli/submit.py", line 247, in main
    wait=args.wait, simple_jar=args.simple_jar)
  File "/home/mohamed/Envs/feedcrm/local/lib/python2.7/site-packages/streamparse/cli/submit.py", line 197, in submit_topology
    with ssh_tunnel(env_config.get("user"), host, 6627, port):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/mohamed/Envs/feedcrm/local/lib/python2.7/site-packages/streamparse/contextmanagers.py", line 45, in ssh_tunnel
    ssh_proc = subprocess.Popen(ssh_cmd, shell=False)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```

Do you have an idea about the origin of this problem?nimbus? ssh access?

**Comment by dan-blanchard** [comment]
Which version of streamparse is this with?

**Comment by dan-blanchard** [comment]
Closing because we never got more info and this was probably with an old version.

**Comment by mlifemaker** [comment]
with 2.1.4 version
