### ISSUE TITLE
Error: channel_new: internal error: channels_alloc 10010 too big.

### ISSUE THREAD

**Issue by cj4777** [Parsely/streamparse#246]
Hi:
     could you give me something to help ?
When I run 'sparse run', it's worked fine, but when i type 'sparse submit' to submit this topology(by the way, nimbus is localhost), and than show me 'port 6627 is aleardy exists', and I changed the nimbus.thrift.port to 6628, then the error message following:

Cleaning from prior builds...
Creating topology Uber-JAR...
Uber-JAR created: /tmp/phpfatal/_build/phpfatal-0.0.1-SNAPSHOT-standalone.jar
Deploying "phpfatal" topology...
ssh tunnel to Nimbus master.hadoop.lan:6627 established.
Routing Python logging to /tmp/phpfatal.
Running lein command to submit topology to nimbus:
lein run -m streamparse.commands.submit_topology/-main topologies/phpfatal.clj --debug --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'topology.python.path="/tmp/phpfatal/phpfatal/bin/python"' --option 'streamparse.log.path="/tmp/phpfatal"' --option 'streamparse.log.max_bytes=100000' --option 'streamparse.log.backup_count=10' --option 'streamparse.log.level="debug"'
{:option {streamparse.log.level debug, streamparse.log.backup_count 10, streamparse.log.max_bytes 100000, streamparse.log.path /tmp/phpfatal, topology.python.path /tmp/phpfatal/phpfatal/bin/python, topology.acker.executors 2, topology.workers 2}, :debug true, :port 6627, :host localhost, :help false}
channel_new: internal error: channels_alloc 10010 too big.
Caught exception: org.apache.thrift7.transport.TTransportException

java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException
 at backtype.storm.StormSubmitter.topologyNameExists (StormSubmitter.java:211)
    backtype.storm.StormSubmitter.submitTopology (StormSubmitter.java:117)
    backtype.storm.StormSubmitter.submitTopology (StormSubmitter.java:70)
    streamparse.commands.submit_topology$submit_topology_BANG_.invoke (submit_topology.clj:23)
    streamparse.commands.submit_topology$_main.doInvoke (submit_topology.clj:86)
    clojure.lang.RestFn.invoke (RestFn.java:2088)
    clojure.lang.Var.invoke (Var.java:489)
    user$eval5.invoke (form-init4525659882773141297.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6619)
    clojure.lang.Compiler.eval (Compiler.java:6609)
    clojure.lang.Compiler.load (Compiler.java:7064)
    clojure.lang.Compiler.loadFile (Compiler.java:7020)
    clojure.main$load_script.invoke (main.clj:294)
    clojure.main$init_opt.invoke (main.clj:299)
    clojure.main$initialize.invoke (main.clj:327)
    clojure.main$null_opt.invoke (main.clj:362)
    clojure.main$main.doInvoke (main.clj:440)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:419)
    clojure.lang.AFn.applyToHelper (AFn.java:163)
    clojure.lang.Var.applyTo (Var.java:532)
    clojure.main.main (main.java:37)
Exception in thread "main" java.lang.NullPointerException
	at streamparse.commands.submit_topology$submit_topology_BANG_.invoke(submit_topology.clj:28)
	at streamparse.commands.submit_topology$_main.doInvoke(submit_topology.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at clojure.lang.Var.invoke(Var.java:489)
	at user$eval5.invoke(form-init4525659882773141297.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Command exited with status 1.

**Comment by cj4777** [comment]
This is what am i says ''port 6627 is aleardy exists"

Cleaning from prior builds...
Creating topology Uber-JAR...
Uber-JAR created: /tmp/phpfatal/_build/phpfatal-0.0.1-SNAPSHOT-standalone.jar
Deploying "phpfatal" topology...
Traceback (most recent call last):
  File "/usr/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==2.1.4', 'console_scripts', 'sparse')()
  File "/usr/local/python2.7/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/cli/sparse.py", line 57, in main
    args.func(args)
  File "/usr/local/python2.7/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/cli/submit.py", line 247, in main
    wait=args.wait, simple_jar=args.simple_jar)
  File "/usr/local/python2.7/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/cli/submit.py", line 197, in submit_topology
    with ssh_tunnel(env_config.get("user"), host, 6627, port):
  File "/usr/local/python2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/python2.7/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/contextmanagers.py", line 32, in ssh_tunnel
    "tunnel to {}:{}.".format(local_port, host, remote_port))
IOError: Local port: 6627 already in use, unable to open ssh tunnel to master.hadoop.lan:6627.

**Comment by mlifemaker** [comment]
check if the port 6627 is busy with netstat:

netstat -nl | grep ':6627'

**Comment by cj4777** [comment]
I thought i can run 'sparse submit' on host of nimbus, finally i change a server to run it, then everything is fine.
and, thx for reply ^_^
