### ISSUE TITLE
How do you use msgpack serializer in 3.0.0dev3

### ISSUE THREAD

**Issue by bobbyrenwick** [Parsely/streamparse#247]
We're trying to test out the new msgpack serializer in `pystorm` but we get the following error in `read_handshake` after adding `"serializer": "msgpack"` to our environment in `config.json`:

```
2016-04-22 13:09:43.467 o.a.s.util [ERROR] Async loop died!
java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:
/opt/envs/test_msgpack/local/lib/python2.7/site-packages/riak/security.py:35: UserWarning: Found OpenSSL 1.0.1f 6 Jan 2014 version, but expected at least OpenSSL 1.0.1g.  Security may not support TLS 1.2.
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/opt/envs/test_msgpack/bin/streamparse_run", line 9, in <module>
    load_entry_point('streamparse==3.0.0.dev3', 'console_scripts', 'streamparse_run')()
  File "/opt/envs/test_msgpack/local/lib/python2.7/site-packages/streamparse/run.py", line 37, in main
    cls(serializer=args.serializer).run()
  File "/opt/envs/test_msgpack/local/lib/python2.7/site-packages/pystorm/component.py", line 474, in run
    storm_conf, context = self.read_handshake()
  File "/opt/envs/test_msgpack/local/lib/python2.7/site-packages/pystorm/component.py", line 303, in read_handshake
    pid_dir, _conf, _context = msg['pidDir'], msg['conf'], msg['context']
TypeError: 'int' object has no attribute '__getitem__'


	at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:91) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:131) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.daemon.executor$fn__8226$fn__8239.invoke(executor.clj:795) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.util$async_loop$fn__554.invoke(util.clj:482) [storm-core-1.0.0.jar:1.0.0]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
```

Are we missing something?

**Comment by dan-blanchard** [comment]
For now we don't actually provide the Java part of the equation, because it's coming in a future Storm release (see apache/storm#1136).  That said, I've personally had success using [pyleus's Java MessagePackSerializer](https://github.com/Yelp/pyleus/blob/64036a8d8ccaa656ddebb3dbd1a7dfb40e15a14a/topology_builder/src/main/java/com/yelp/pyleus/serializer/MessagePackSerializer.java) by:

1. Creating a `src/java/com/yelp/pyleus/serializer/` in your streamparse project folder.
2. Copying `MessagePackSerializer.java` into that directory.
3. Adding these lines to your `project.clj` file:

    ```
    :java-source-paths ["src/java"]
  :javac-options ["-target" "1.7" "-source" "1.7" "-Xlint:-options"]
  :aot :all
    ```
4.  Adding `[org.msgpack/msgpack "0.6.12"]` to your `:dependencies` list in your project.clj.  It should look something like this (where the Storm version matches your cluster):

    ```
:dependencies [
                 [org.apache.storm/storm-core "1.0.0"]
                 [org.msgpack/msgpack "0.6.12"]
                 ]
    ```
5.  Adding `-o topology.multilang.serializer=com.yelp.pyleus.serializer.MessagePackSerializer` to your call to `sparse submit`.

**Comment by bobbyrenwick** [comment]
Hi @dan-blanchard,

Thanks for the super quick response! Unfortunately I've followed those steps and ended up with a `project.clj` that looks like:

```clj
(defproject streamy "0.0.1-SNAPSHOT"
  :source-paths ["topologies"]
  :resource-paths ["_resources"]
  :target-path "_build"
  :min-lein-version "2.0.0"
  :jvm-opts ["-client"]
  :dependencies  [[org.apache.storm/storm-core "1.0.0"]
                  [org.apache.storm/flux-core "1.0.0"]
                  [org.msgpack/msgpack "0.6.12"]
                  ]
  :java-source-paths ["src/java"]
  :javac-options ["-target" "1.7" "-source" "1.7" "-Xlint:-options"]
  :aot :all
  :jar-exclusions     [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  :uberjar-exclusions [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  )
```

but on submitting, it seems that the `MessagePackSerializer.java` can't find the dependencies that I assume `lein` downloads automatically:

```
Creating topology JAR...

Warning: local() encountered an error (return code 1) while executing 'lein jar'

Traceback (most recent call last):
  File "/opt/env/streamy/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/opt/env/streamy/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/opt/env/streamy/lib/python2.7/site-packages/streamparse/cli/submit.py", line 262, in main
    wait=args.wait, simple_jar=args.simple_jar)
  File "/opt/env/streamy/lib/python2.7/site-packages/streamparse/cli/submit.py", line 215, in submit_topology
    topology_jar = jar_for_deploy(simple_jar=simple_jar)
  File "/opt/env/streamy/lib/python2.7/site-packages/streamparse/cli/jar.py", line 38, in jar_for_deploy
    res.stderr))
RuntimeError: Unable to run 'lein jar'!
STDOUT:

STDERR:
Compiling 1 source files to /opt/streamy/_build/classes
/opt/streamy/src/java/com/yelp/pyleus/serializer/MessagePackSerializer.java:12: error: package backtype.storm.multilang does not exist
import backtype.storm.multilang.BoltMsg;
```

Do you have any ideas on how to get `javac` to find the other dependencies?

**Comment by dan-blanchard** [comment]
That's what I get for changing the storm version in my example from what we actually use (still stuck on 0.9.5 at the moment)! 😄 

Anyway, your issue is that that MessagePackSerializer from pyleus isn't Storm 1.0 compatible, because it still uses the old package names for things.  If you replace everything that says `backtype` with `org.apache`, you should be good to go, since I think that's all that's *really* changed with the Java API.

**Comment by bobbyrenwick** [comment]
Thanks @dan-blanchard, that got it up and running!
