### ISSUE TITLE
streamparse + pykafka error

### ISSUE THREAD

**Issue by daiguadaidai** [Parsely/streamparse#250]
Hi
I want use pykafka in spout, but get to error
(I already install pykafka in virtualenvs and OS python site-packages)
**these are my python module:**
**IN OS:**
```
[root@storm_2 wordcount]# ls /usr/lib/python2.7/site-packages/pykafka
balancedconsumer.py   cli         cluster.pyc    connection.pyc  handlers.pyc                managedbalancedconsumer.pyc  partition.pyc  protocol.pyc        test
balancedconsumer.pyc  client.py   common.py      exceptions.py   __init__.py                 partitioners.py              producer.py    rdkafka             topic.py
broker.py             client.pyc  common.pyc     exceptions.pyc  __init__.pyc                partitioners.pyc             producer.pyc   simpleconsumer.py   topic.pyc
broker.pyc            cluster.py  connection.py  handlers.py     managedbalancedconsumer.py  partition.py                 protocol.py    simpleconsumer.pyc  utils
```
**streamparse virtualenvs: **
```
[root@storm_2 wordcount]# ls /tmp/storm/stream/virtualenvs/wordcount/lib/python2.7/site-packages/
contextlib2-0.5.3.dist-info  Fabric-1.11.1.dist-info   kazoo                      prettytable-0.7.2.dist-info  setuptools-21.0.0.dist-info  tabulate.py
contextlib2.py               gevent                    kazoo-2.2.1.dist-info      prettytable.py               simplejson                   tabulate.pyc
contextlib2.pyc              gevent-1.1.0.dist-info    markupsafe                 prettytable.pyc              simplejson-3.8.2.dist-info   test
Crypto                       greenlet-0.4.9.dist-info  MarkupSafe-0.23.dist-info  pycrypto-2.6.1.dist-info     six-1.10.0.dist-info         tests
easy_install.py              greenlet.so               paramiko                   pykafka                      six.py                       wheel
easy_install.pyc             invoke                    paramiko-1.17.0.dist-info  pykafka-2.3.1.dist-info      six.pyc                      wheel-0.29.0.dist-info
ecdsa                        invoke-0.12.2.dist-info   pip                        requests                     streamparse
ecdsa-0.13.dist-info         jinja2                    pip-8.1.1.dist-info        requests-2.10.0.dist-info    streamparse-2.1.4.dist-info
fabric                       Jinja2-2.8.dist-info      pkg_resources              setuptools                   tabulate-0.7.5.dist-info
```
**my spout file:**
```
[root@storm_2 spouts]# pwd
/u01/storm_project/wordcount/src/spouts
[root@storm_2 spouts]# cat words.py 
from __future__ import absolute_import, print_function, unicode_literals

import itertools
from streamparse.spout import Spout
from pykafka import KafkaClient
import simplejson as json

class WordSpout(Spout):

    def initialize(self, stormconf, context):
        # self.words = itertools.cycle(['dog', 'cat',
        #                               'zebra', 'elephant'])
        client = KafkaClient(hosts="10.10.10.11:9092")
        topic = client.topics["test"]
        self.balanced_consumer = topic.get_balanced_consumer(
            consumer_group="test_group",
            auto_commit_enable=True,
            zookeeper_connect="storm_1:2181,storm_2:2181,storm_3:2181"
        )

    def next_tuple(self):
        # word = next(self.words)
        # self.emit([word])
        message = self.balanced_consumer.consume()
        word = message.value
        with open("/tmp/storm.log", "a") as f:
            f.write(word)
        self.emit([word])
```
**sparse run error:**
```
java.lang.Exception: Shell Process Exception: Python TypeError raised
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 487, in run
    self.initialize(storm_conf, context)
  File "spouts/words.py", line 14, in initialize
    topic = client.topics["test"]
  File "/usr/lib/python2.7/site-packages/pykafka/cluster.py", line 56, in __getitem__
    "got '%s'", type(key))
TypeError: ("TopicDict.__getitem__ accepts a bytes object, but it got '%s'", <type 'unicode'>)

        at backtype.storm.spout.ShellSpout.handleError(ShellSpout.java:212) [storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:158) [storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:91) [storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.daemon.executor$fn__3371$fn__3386$fn__3415.invoke(executor.clj:565) [storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) [storm-core-0.9.5.jar:0.9.5]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
15388 [Thread-16-word-spout] ERROR backtype.storm.util - Async loop died!
java.lang.RuntimeException: pid:7580, name:word-spout exitCode:-1, errorString: 
        at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:180) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:91) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.daemon.executor$fn__3371$fn__3386$fn__3415.invoke(executor.clj:565) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) ~[storm-core-0.9.5.jar:0.9.5]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.7.0_79]
        at java.io.FileOutputStream.write(FileOutputStream.java:345) ~[na:1.7.0_79]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.7.0_79]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.7.0_79]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.7.0_79]
        at backtype.storm.multilang.JsonSerializer.writeString(JsonSerializer.java:96) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.multilang.JsonSerializer.writeMessage(JsonSerializer.java:89) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.multilang.JsonSerializer.writeSpoutMsg(JsonSerializer.java:81) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.utils.ShellProcess.writeSpoutMsg(ShellProcess.java:112) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:142) ~[storm-core-0.9.5.jar:0.9.5]
        ... 5 common frames omitted
15391 [Thread-16-word-spout] ERROR backtype.storm.daemon.executor - 
java.lang.RuntimeException: pid:7580, name:word-spout exitCode:-1, errorString: 
        at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:180) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:91) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.daemon.executor$fn__3371$fn__3386$fn__3415.invoke(executor.clj:565) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) ~[storm-core-0.9.5.jar:0.9.5]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.7.0_79]
        at java.io.FileOutputStream.write(FileOutputStream.java:345) ~[na:1.7.0_79]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.7.0_79]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.7.0_79]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.7.0_79]
        at backtype.storm.multilang.JsonSerializer.writeString(JsonSerializer.java:96) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.multilang.JsonSerializer.writeMessage(JsonSerializer.java:89) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.multilang.JsonSerializer.writeSpoutMsg(JsonSerializer.java:81) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.utils.ShellProcess.writeSpoutMsg(ShellProcess.java:112) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:142) ~[storm-core-0.9.5.jar:0.9.5]
        ... 5 common frames omitted
15432 [Thread-16-word-spout] ERROR backtype.storm.util - Halting process: ("Worker died")
java.lang.RuntimeException: ("Worker died")
        at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) [storm-core-0.9.5.jar:0.9.5]
        at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
        at backtype.storm.daemon.worker$fn__4694$fn__4695.invoke(worker.clj:493) [storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.daemon.executor$mk_executor_data$fn__3272$fn__3273.invoke(executor.clj:240) [storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.util$async_loop$fn__460.invoke(util.clj:473) [storm-core-0.9.5.jar:0.9.5]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Traceback (most recent call last):
  File "/usr/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==2.1.4', 'console_scripts', 'sparse')()
  File "/usr/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 57, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/streamparse/cli/run.py", line 81, in main
    debug=args.debug)
  File "/usr/lib/python2.7/site-packages/streamparse/cli/run.py", line 52, in run_local_topology
    run(full_cmd)
  File "/usr/lib/python2.7/site-packages/invoke/__init__.py", line 27, in run
    return Context().run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 302, in run
    raise Failure(result)
invoke.exceptions.Failure: Command execution failure!

Exit code: 1

Stderr:
```
what should I do? **or** any idea using kafka in streamparse?

**Comment by dan-blanchard** [comment]
pykafka requires `byte` strings for specifying consumer group and topic, so you want to change:

```py
        client = KafkaClient(hosts="10.10.10.11:9092")
        topic = client.topics["test"]
        self.balanced_consumer = topic.get_balanced_consumer(
            consumer_group="test_group",
            auto_commit_enable=True,
            zookeeper_connect="storm_1:2181,storm_2:2181,storm_3:2181"
        )
```

to 

```py
        client = KafkaClient(hosts="10.10.10.11:9092")
        topic = client.topics[b"test"]
        self.balanced_consumer = topic.get_balanced_consumer(
            consumer_group=b"test_group",
            auto_commit_enable=True,
            zookeeper_connect="storm_1:2181,storm_2:2181,storm_3:2181"
        )
```
