### ISSUE TITLE
3.0.0.dev3 sparse run - version search pattern error

### ISSUE THREAD

**Issue by Darkless012** [Parsely/streamparse#254]
sparse run

Traceback (most recent call last):
  File "/home/darkless/.virtualenvs/sparse3/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 85, in main
    debug=args.debug)
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 31, in run_local_topology
    local_version = local_storm_version()
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/util.py", line 271, in local_storm_version
    return parse_version(re.findall(pattern, res.stdout)[0])
IndexError: list index out of range

**Comment by Darkless012** [comment]
https://github.com/Parsely/streamparse/pull/255

**Comment by dan-blanchard** [comment]
Which version of Storm is this with?

**Comment by Darkless012** [comment]
print(res.stdout)

Running: java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/opt/apache-storm-1.0.1 -Dstorm.log.dir=/opt/apache-storm-1.0.1/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /opt/apache-storm-1.0.1/lib/reflectasm-1.10.1.jar:/opt/apache-storm-1.0.1/lib/kryo-3.0.3.jar:/opt/apache-storm-1.0.1/lib/log4j-over-slf4j-1.6.6.jar:/opt/apache-storm-1.0.1/lib/clojure-1.7.0.jar:/opt/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar:/opt/apache-storm-1.0.1/lib/servlet-api-2.5.jar:/opt/apache-storm-1.0.1/lib/disruptor-3.3.2.jar:/opt/apache-storm-1.0.1/lib/objenesis-2.1.jar:/opt/apache-storm-1.0.1/lib/storm-core-1.0.1.jar:/opt/apache-storm-1.0.1/lib/slf4j-api-1.7.7.jar:/opt/apache-storm-1.0.1/lib/storm-rename-hack-1.0.1.jar:/opt/apache-storm-1.0.1/lib/log4j-api-2.1.jar:/opt/apache-storm-1.0.1/lib/log4j-core-2.1.jar:/opt/apache-storm-1.0.1/lib/minlog-1.3.0.jar:/opt/apache-storm-1.0.1/lib/asm-5.0.3.jar:/opt/apache-storm-1.0.1/conf org.apache.storm.utils.VersionInfo
Storm 1.0.1
URL https://git-wip-us.apache.org/repos/asf/storm.git -r b5c16f919ad4099e6fb25f1095c9af8b64ac9f91
Branch (no branch)
Compiled by tgoetz on 2016-04-29T20:44Z
From source with checksum 1aea9df01b9181773125826339b9587e

    print(re.findall(pattern, res.stdout))

[]

**Comment by Darkless012** [comment]
Version 1.0.1
OS: Linux Mint 17.2 (Ubuntu 14.04 base)
bash

**Comment by Lordtien** [comment]
sparse run
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/run.py", line 85, in main
    debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/run.py", line 31, in run_local_topology
    local_version = local_storm_version()
  File "/usr/local/lib/python2.7/dist-packages/streamparse/util.py", line 271, in local_storm_version
    return parse_version(re.findall(pattern, res.stdout, flags=re.MULTILINE)[0])
IndexError: list index out of range

**Comment by ReedAnders** [comment]
The regex pattern expects the res.stdout value to contain "Storm x.x.x" but some versions only emit "x.x.x". Before it's patched, you can edit[ line 271](https://github.com/Parsely/streamparse/blob/master/streamparse/util.py#L285) as:

`parse_version(re.findall(pattern, "Storm [x.x.x]", flags=re.MULTILINE)[0])`

For example:
`parse_version(re.findall(pattern, "Storm 0.9.7", flags=re.MULTILINE)[0])`

**Comment by dan-blanchard** [comment]
@ReedAnders, could you point to an example version that doesn't contain the Storm prefix in the output? I have not been able to find one.

**Comment by ReedAnders** [comment]
Storm 0.9.7 gave me a one line output of "0.9.7" for the version command.
