### ISSUE TITLE
3.0.0.dev3 TypeError: Flux does not currently support ShellBolts with multiple streams. 

### ISSUE THREAD

**Issue by Darkless012** [Parsely/streamparse#259]
```
sparse run
Cleaning from prior builds...
Creating topology Uber-JAR...
Uber-JAR created: /home/darkless/projects/sparse_testing/test/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar
Removing _resources temporary directory...done
Traceback (most recent call last):
  File "/home/darkless/.virtualenvs/sparse3/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 85, in main
    debug=args.debug)
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 49, in run_local_topology
    topology_flux_dict = topology_class.to_flux_dict(name)
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/dsl/topology.py", line 254, in to_flux_dict
    flux_dict['spouts'].append(cls._spec_to_flux_dict(spec))
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/dsl/topology.py", line 205, in _spec_to_flux_dict
    .format(spec))
TypeError: Flux does not currently support ShellBolts with multiple streams. Given: ShellSpoutSpec(XWordSpout, par=1, name='word_spout', inputs={}, outputs={'second': StreamInfo(output_fields=['word'], direct=False), 'first': StreamInfo(output_fields=['word'], direct=False)}, component_object=ComponentObject(shell=ShellComponent(execution_command='streamparse_run', script='wordcount.XWordSpout'), java_object=None, serialized_java=None), common=ComponentCommon(inputs={}, json_conf='{}', streams={'second': StreamInfo(output_fields=['word'], direct=False), 'first': StreamInfo(output_fields=['word'], direct=False)}, parallelism_hint=1), config='{}')

```

**Comment by Darkless012** [comment]
I have modified wordcount topology for better reproducibility.
Here is respective topologies/wordcount.py:

```
"""
Word count topology
"""

from streamparse import Grouping, Topology, Stream

from bolts.wordcount import WordCountBolt
from spouts.words import WordSpout


class WordCount(Topology):
    class XWordSpout(WordSpout):
        outputs = [
            Stream(fields=['word'],
                   name='first',),
            Stream(fields=['word'],
                   name='second',),
        ]

    word_spout = XWordSpout.spec()
    first_count_bolt = WordCountBolt.spec(name=b"wordcount_first", inputs={word_spout['first']: Grouping.SHUFFLE},
                                    par=2)
    second_count_bolt = WordCountBolt.spec(name=b"wordcount_second", inputs={word_spout['second']: Grouping.SHUFFLE},
                                    par=2)

```
