### ISSUE TITLE
sparse run does not work out of the box (quickstart)

### ISSUE THREAD

**Issue by daTokenizer** [Parsely/streamparse#270]
```pytb
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/sparse.py", line 53, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/run.py", line 81, in main
    debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/run.py", line 20, in run_local_topology
    prepare_topology()
  File "/usr/local/lib/python2.7/dist-packages/streamparse/util.py", line 198, in prepare_topology
    shutil.copytree("src", "_resources/resources")
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'src'
```

**Comment by dan-blanchard** [comment]
Could provide a little more info? Were you running this from within your project folder? Was this with the quickstart project? What version was this with?

**Comment by daTokenizer** [comment]
LOL
as i was trying to figure out what happens i realized the student did not `cd` into the dir.. maybe this ticket should become "add a verbose exception when using sparse run from a non-sparse dir"
