### ISSUE TITLE
Error while executing stream parse wordcount application

### ISSUE THREAD

**Issue by uddhavarote** [Parsely/streamparse#272]
I have installed Apache Storm (v1.0.1) on El Capitan. I am using parsely's streamparse framework to build python based topologies. To start with, I ran 'word count' application but the execution aborts.

Following is the chunk of the complete trace:

Parsing file: /var/folders/lc/42tpn2n55ydb0bqjnml1clww0000gn/T/tmppHZqlN.yaml
632  [main] INFO  o.a.s.f.p.FluxParser - loading YAML from input stream...
634  [main] INFO  o.a.s.f.p.FluxParser - Not performing property substitution.
634  [main] INFO  o.a.s.f.p.FluxParser - Not performing environment variable substitution.
717  [main] INFO  o.a.s.f.FluxBuilder - Detected DSL topology...
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.apache.storm.topology.BaseConfigurationDeclarer.<init>(BaseConfigurationDeclarer.java:26)
    at org.apache.storm.topology.TopologyBuilder$ConfigGetter.<init>(TopologyBuilder.java:454)
    at org.apache.storm.topology.TopologyBuilder$SpoutGetter.<init>(TopologyBuilder.java:471)
    at org.apache.storm.topology.TopologyBuilder.setSpout(TopologyBuilder.java:343)
    at org.apache.storm.flux.FluxBuilder.buildSpouts(FluxBuilder.java:353)
    at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:84)
    at org.apache.storm.flux.Flux.runCli(Flux.java:153)
    at org.apache.storm.flux.Flux.main(Flux.java:98)
Caused by: while scanning a simple key
 in 'reader', line 52, column 1:
    storm.zookeeper.port=2181
    ^
could not found expected ':'
 in 'reader', line 53, column 1:
    nimbus.host: "localhost"
    ^

    at org.apache.storm.shade.org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:460)
    at org.apache.storm.shade.org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
    at org.apache.storm.shade.org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
    at org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:532)
    at org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
    at org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
    at org.apache.storm.shade.org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:203)
    at org.apache.storm.shade.org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:157)
    at org.apache.storm.shade.org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
    at org.apache.storm.shade.org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
    at org.apache.storm.shade.org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
    at org.apache.storm.shade.org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
    at org.apache.storm.shade.org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
    at org.apache.storm.shade.org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
    at org.apache.storm.shade.org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
    at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:290)
    at org.apache.storm.utils.Utils.readStormConfig(Utils.java:391)
    at org.apache.storm.utils.Utils.<clinit>(Utils.java:119)
    ... 8 more

Fatal error: local() encountered an error (return code 1) while executing 'storm jar /storm/streamparse/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /var/folders/lc/42tpn2n55ydb0bqjnml1clww0000gn/T/tmppHZqlN.yaml'

Aborting.
Where could have the configuration possibly gone wrong? Nimbus/supervisor/ui services are running.

Following is the storm.yam file

storm.zookeeper.servers:

     - "localhost"

storm.zookeeper.port: 2181

nimbus.host: "localhost"

storm.local.dir: "/some/storm/dir"

java.library.path: "/my/java/home"

supervisor.slots.ports:

     - 6700

     - 6701

     - 6702

     - 6703

worker.childopts: "-Xmx768m"

nimbus.childopts: "-Xmx512m"

supervisor.childopts: "-Xmx256m"
The 'wordcount' project.clj file consists of following dependencies:

storm-core:1.0.1

flux-core:1.0.1

**Comment by obiii** [comment]
How did you solve this problem? I am facing same issue.
