### ISSUE TITLE
Streamparse Submission Errors - Storm 1.0.1

### ISSUE THREAD

**Issue by Tom-Gorup** [Parsely/streamparse#294]
When I attempt to submit a topology with `sparse submit -n wordcount -e prod` using the default project.clj (which uses storm-core 0.9.5), I receive the below errors in worker.log.

**project.clj**
```
  :dependencies  [[org.apache.storm/storm-core "0.9.5"]
                  [com.parsely/streamparse "0.0.4-SNAPSHOT"]
                  ]
```

**worker.log**
```
2016-07-29 16:52:47.107 o.a.s.d.executor [INFO] Loading executor count-bolt:[3 3]
2016-07-29 16:52:47.124 o.a.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.RuntimeException: java.io.InvalidClassException: clojure.lang.APersistentMap; local class incompatible: stream classdesc serialVersionUID = 8648225932767613808, local class serialVersionUID = 6736310834519110267
    at org.apache.storm.utils.Utils.javaDeserialize(Utils.java:179) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.utils.Utils.getSetComponentObject(Utils.java:430) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.task$get_task_object.invoke(task.clj:74) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.task$mk_task_data$fn__7601.invoke(task.clj:177) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.util$assoc_apply_self.invoke(util.clj:930) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.task$mk_task_data.invoke(task.clj:170) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.task$mk_task.invoke(task.clj:181) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.executor$mk_executor$fn__7820.invoke(executor.clj:371) ~[storm-core-1.0.1.jar:1.0.1]
    at clojure.core$map$fn__4553.invoke(core.clj:2622) ~[clojure-1.7.0.jar:?]
    at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.7.0.jar:?]
    at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.7.0.jar:?]
    at clojure.lang.RT.seq(RT.java:507) ~[clojure-1.7.0.jar:?]
    at clojure.core$seq__4128.invoke(core.clj:137) ~[clojure-1.7.0.jar:?]
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~[clojure-1.7.0.jar:?]
    at clojure.core.protocols$fn__6506.invoke(protocols.clj:101) ~[clojure-1.7.0.jar:?]
    at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13) ~[clojure-1.7.0.jar:?]
    at clojure.core$reduce.invoke(core.clj:6519) ~[clojure-1.7.0.jar:?]
    at clojure.core$into.invoke(core.clj:6600) ~[clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.executor$mk_executor.invoke(executor.clj:372) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.worker$fn__8450$exec_fn__2461__auto__$reify__8452$iter__8457__8461$fn__8462.invoke(worker.clj:637) ~[storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.7.0.jar:?]
    at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.7.0.jar:?]
    at clojure.lang.RT.seq(RT.java:507) ~[clojure-1.7.0.jar:?]
    at clojure.core$seq__4128.invoke(core.clj:137) ~[clojure-1.7.0.jar:?]
    at clojure.core$dorun.invoke(core.clj:3009) ~[clojure-1.7.0.jar:?]
    at clojure.core$doall.invoke(core.clj:3025) ~[clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.worker$fn__8450$exec_fn__2461__auto__$reify__8452.run(worker.clj:637) ~[storm-core-1.0.1.jar:1.0.1]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_101]
    at javax.security.auth.Subject.doAs(Subject.java:415) ~[?:1.7.0_101]
    at org.apache.storm.daemon.worker$fn__8450$exec_fn__2461__auto____8451.invoke(worker.clj:609) ~[storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.AFn.applyToHelper(AFn.java:178) ~[clojure-1.7.0.jar:?]
    at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.7.0.jar:?]
    at clojure.core$apply.invoke(core.clj:630) ~[clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.worker$fn__8450$mk_worker__8545.doInvoke(worker.clj:583) [storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.worker$_main.invoke(worker.clj:771) [storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.7.0.jar:?]
    at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.worker.main(Unknown Source) [storm-core-1.0.1.jar:1.0.1]
Caused by: java.io.InvalidClassException: clojure.lang.APersistentMap; local class incompatible: stream classdesc serialVersionUID = 8648225932767613808, local class serialVersionUID = 6736310834519110267
    at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:612) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1779) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2016) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1806) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353) ~[?:1.7.0_101]
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373) ~[?:1.7.0_101]
    at org.apache.storm.utils.Utils.javaDeserialize(Utils.java:175) ~[storm-core-1.0.1.jar:1.0.1]
    ... 38 more
2016-07-29 16:52:47.143 o.a.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
    at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) [storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.worker$fn__8450$mk_worker__8545.doInvoke(worker.clj:583) [storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.worker$_main.invoke(worker.clj:771) [storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.7.0.jar:?]
    at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.worker.main(Unknown Source) [storm-core-1.0.1.jar:1.0.1]
```

When I attempt the same thing, but switching the storm-core to 1.0.1 I get the below set of errors as output.

**project.clj**
```
  :dependencies  [[org.apache.storm/storm-core "1.0.1"]
                  [com.parsely/streamparse "0.0.4-SNAPSHOT"]
                  ]
```

**worker.log**
```
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(/tmp/form-init7408633810021040114.clj:1:73)
    at clojure.lang.Compiler.load(Compiler.java:7239)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at clojure.lang.RT.classForName(RT.java:2154)
    at clojure.lang.RT.classForName(RT.java:2163)
    at clojure.lang.RT.loadClassForName(RT.java:2182)
    at clojure.lang.RT.load(RT.java:436)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval5$fn__7.invoke(form-init7408633810021040114.clj:1)
    at user$eval5.invoke(form-init7408633810021040114.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6772)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    ... 11 more
Caused by: java.io.FileNotFoundException: Could not locate backtype/storm/clojure__init.class or backtype/storm/clojure.clj on classpath.
    at clojure.lang.RT.load(RT.java:449)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5753)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:634)
    at clojure.core$use.doInvoke(core.clj:5843)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at streamparse.commands.submit_topology$loading__4910__auto__.invoke(submit_topology.clj:1)
    at streamparse.commands.submit_topology__init.load(Unknown Source)
    at streamparse.commands.submit_topology__init.<clinit>(Unknown Source)
    ... 36 more
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==2.1.4', 'console_scripts', 'sparse')()
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/sparse.py", line 57, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/submit.py", line 247, in main
    wait=args.wait, simple_jar=args.simple_jar)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/submit.py", line 209, in submit_topology
    host=host, port=port)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/submit.py", line 139, in _submit_topology
    run(full_cmd)
  File "/usr/local/lib/python2.7/dist-packages/invoke/__init__.py", line 32, in run
    return Context().run(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/runners.py", line 363, in run
    raise Failure(result)
invoke.exceptions.Failure: Command execution failure!
 
Exit code: 1
 
Stderr:
 
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(/tmp/form-init7408633810021040114.clj:1:73)
    at clojure.lang.Compiler.load(Compiler.java:7239)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at clojure.lang.RT.classForName(RT.java:2154)
    at clojure.lang.RT.classForName(RT.java:2163)
    at clojure.lang.RT.loadClassForName(RT.java:2182)
    at clojure.lang.RT.load(RT.java:436)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval5$fn__7.invoke(form-init7408633810021040114.clj:1)
    at user$eval5.invoke(form-init7408633810021040114.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6772)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    ... 11 more
Caused by: java.io.FileNotFoundException: Could not locate backtype/storm/clojure__init.class or backtype/storm/clojure.clj on classpath.
    at clojure.lang.RT.load(RT.java:449)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5753)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:634)
    at clojure.core$use.doInvoke(core.clj:5843)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at streamparse.commands.submit_topology$loading__4910__auto__.invoke(submit_topology.clj:1)
    at streamparse.commands.submit_topology__init.load(Unknown Source)
    at streamparse.commands.submit_topology__init.<clinit>(Unknown Source)
    ... 36 more
```

Is streamparse compatible with storm 1.0.1?

Running Versions:
- Storm 1.0.1
- streamparse 2.1.4

**Comment by dan-blanchard** [comment]
streamparse 2.1.4 is not compatible with Storm 1.x.  Please upgrade to streamparse 3.0.0.
