### ISSUE TITLE
kafka-jvm example fails during 'vagrant up'

### ISSUE THREAD

**Issue by saritasa** [Parsely/streamparse#300]
Guys -> Pls see log below. Any ideas?

```ruby
[dmitry:~/Projects/experiments/storm/streamparse/examples/kafka-jvm] (master)$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'streamparse-box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'streamparse-box' (v0) for provider: virtualbox
    default: Downloading: http://files.vagrantup.com/precise64.box
==> default: Successfully added box 'streamparse-box' (v0) for 'virtualbox'!
==> default: Importing base box 'streamparse-box'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: streamparse-kafka-storm-box
==> default: Auto-generating node name for Chef...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
    default: Warning: Connection timeout. Retrying...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 5.0
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/dmitry/Projects/experiments/storm/streamparse/examples/kafka-jvm
    default: /tmp/vagrant-chef/14637904b130bb1b5cd60c584b14f5e5/cookbooks => /home/dmitry/Projects/experiments/storm/streamparse/examples/kafka-jvm/chef/cookbooks
==> default: Running provisioner: chef_solo...
    default: Installing Chef (latest)...
==> default: Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2016-08-20T00:50:26+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /tmp/vagrant-chef/14637904b130bb1b5cd60c584b14f5e5
==> default:   One version per cookbook
==> default: [2016-08-20T00:50:26+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 12.14.16
==> default: [2016-08-20T00:50:26+00:00] INFO: *** Chef 12.14.16 ***
==> default: [2016-08-20T00:50:26+00:00] INFO: Platform: x86_64-linux
==> default: [2016-08-20T00:50:26+00:00] INFO: Chef-client pid: 2014
==> default: [2016-08-20T00:50:28+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/vagrant-9abea9f1
==> default: [2016-08-20T00:50:28+00:00] INFO: HTTP Request Returned 404 Not Found: Parent not found: chefzero://localhost:8889/nodes
==> default: 
==> default: ================================================================================
==> default: 
==> default: Chef encountered an error attempting to load the node data for "vagrant-9abea9f1"
==> default: ================================================================================
==> default: 
==> default: 
==> default: Resource Not Found:
==> default: -------------------
==> default: The server returned a HTTP 404. This usually indicates that your chef_server_url is incorrect.
==> default: 
==> default: 
==> default: Relevant Config Settings:
==> default: -------------------------
==> default: chef_server_url "chefzero://localhost:8889"
==> default: 
==> default: 
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
==> default: 
==> default: 
==> default: 
==> default: Running handlers:
==> default: [2016-08-20T00:50:28+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: 
==> default: [2016-08-20T00:50:28+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 01 seconds
==> default: [2016-08-20T00:50:28+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-20T00:50:28+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-20T00:50:28+00:00] ERROR: 404 "Not Found"
==> default: [2016-08-20T00:50:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by saritasa** [comment]
okay figured out. Had to install vagrant 1.8.5 + VirtualBox 5.1.4 from rpms instead default fedora repos.
