### ISSUE TITLE
kafka-jvm example 'invoke seed_kafka' creates 'TypeError: Tasks must have an initial Context argument!'

### ISSUE THREAD

**Issue by saritasa** [Parsely/streamparse#301]
```bash
(storm) [dmitry:~/Projects/experiments/storm/streamparse/examples/kafka-jvm] (master)$ invoke seed_kafka
Traceback (most recent call last):
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/tasks.py", line 141, in argspec
    context_arg = arg_names.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmitry/.pyenv/versions/storm/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/dmitry/.pyenv/versions/3.5.2/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/dmitry/.pyenv/versions/3.5.2/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dmitry/Projects/experiments/storm/streamparse/examples/kafka-jvm/tasks.py", line 63, in <module>
    def seed_kafka(kafka_hosts=None, topic_name=None, num_pixels=100000):
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/tasks.py", line 267, in task
    return Task(args[0], **kwargs)
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!

```

```bash
(storm) [dmitry:~/Projects/experiments/storm/streamparse/examples/kafka-jvm] (master)$ pip list
ecdsa (0.13)
Fabric3 (1.12.post1)
invoke (0.13.0)
Jinja2 (2.8)
kafka-python (0.9.3)
MarkupSafe (0.23)
msgpack-python (0.4.8)
paramiko (1.17.2)
pip (8.1.2)
ply (3.8)
prettytable (0.7.2)
pycrypto (2.6.1)
pystorm (3.0.1)
requests (2.11.1)
ruamel.yaml (0.12.4)
setuptools (20.10.1)
simplejson (3.8.2)
six (1.10.0)
streamparse (3.0.1)
thriftpy (0.3.8)

```

**Comment by dan-blanchard** [comment]
Invoke changed their API yet again, and this was the last bit of our codebase that still used it, so I switched this example to using fabric for running this task in #310.  This will be fixed in the next release (which will be very soon).
