### ISSUE TITLE
Provide example of mixed Java + Python topology using storm-kafka

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#31]
Requested on the mailing list:

> I am looking forward to understand how I can use clojure DSL to submit a a topology which has spout written in Java and Bolts written in Python.

The best first example would be to use the [new official Kafka spout (storm-kafka)][storm-kafka] that is now included in Storm's 0.9.2 release. This combined with Python bolts processing the data from the Kafka spout would be the best first Python + Java interop example for streamparse, I think.

[storm-kafka]: https://github.com/apache/incubator-storm/tree/v0.9.2-incubating/external/storm-kafka

**Comment by amontalenti** [comment]
There is another pull request on-going over at our Pyleus friends for integrating Java components via the YAML DSL. See https://github.com/Yelp/pyleus/pull/99

**Comment by dan-blanchard** [comment]
The example we have works fine now, so I'm closing this.

**Comment by CaledoniaProject** [comment]
Should I reopen this one? The kafka-jvm example does not run .. as dan removed the pixelcount.clj from the topology directory, 

When I run `sparse run`, it says there's no topology defined.

Someone please help?

https://github.com/Parsely/streamparse/issues/219

**Comment by pythonishvili** [comment]
Hello, I'm running into this problem when playing around with kafka example:
```
$ invoke seed_kafka
Traceback (most recent call last):
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/tasks.py", line 141, in argspec
    context_arg = arg_names.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/remy/.virtualenvs/storm/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/remy/.virtualenvs/storm/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/remy/.virtualenvs/storm/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/remy/workspace/streamparse/examples/kafka-jvm/tasks.py", line 63, in <module>
    def seed_kafka(kafka_hosts=None, topic_name=None, num_pixels=100000):
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/tasks.py", line 267, in task
    return Task(args[0], **kwargs)
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/home/remy/.virtualenvs/storm/lib/python3.4/site-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
```

Any help, highly appreciated :)
