### ISSUE TITLE
TTransportException when submitting to prod

### ISSUE THREAD

**Issue by SimSimY** [Parsely/streamparse#313]
Hi All

I am tring to deploy the world count demo to our (fresh) storm cluster in aws. 

I use the quick start as is and the config.json is pretty straight forward:
```
{
    "serializer": "json",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "storm",
            "ssh_password": "",
            "nimbus": "s1.eu-west-1.compute.internal",
            "workers": [
                "s1.eu-west-1.compute.internal",
                "s2.eu-west-1.compute.internal",
                "s3.eu-west-1.compute.internal",
                "s4.eu-west-1.compute.internal",
                "s5.eu-west-1.compute.internal",
                "s6.eu-west-1.compute.internal"
            ],
            "log": {
                "path": "/opt/storm/logs",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "info"
            },
            "virtualenv_root": "/opt/storm/topologies/wc"
        }
    }
}
```

The submit script works great up to the part where it tires to  actually submit the topology:

```
Cleaning from prior builds...
Creating topology JAR...
JAR created: /home/sim/wc/ororo-0.0.1-SNAPSHOT.jar
Removing _resources temporary directory...done
Deploying "wordcount" topology...
ssh tunnel to Nimbus s1.eu-west-1.compute.internal:6627 established.
Uploading topology jar /home/sim/wc/ororo-0.0.1-SNAPSHOT.jar to assigned location: /opt/storm/apache-storm-inst/storm-local/nimbus/inbox/stormjar-1f53f1be-f9e6-45b2-ba1b-ea1ad3ce2d09.jar
Uploaded 3397/3397 bytes
Routing Python logging to /opt/storm/logs.
Submitting wordcount topology to nimbus...Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==3.1.1', 'console_scripts', 'sparse')()
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/submit.py", line 244, in main
    override_name=args.override_name)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/submit.py", line 209, in submit_topology
    env_config, nimbus_client, options=options)
  File "/usr/local/lib/python2.7/dist-packages/streamparse/cli/submit.py", line 96, in _submit_topology
    topology=topology_class.thrift_topology)
  File "/usr/local/lib/python2.7/dist-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/local/lib/python2.7/dist-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6325)
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1546)
  File "thriftpy/transport/framed/cyframed.pyx", line 48, in thriftpy.transport.framed.cyframed.TCyFramedTransport.c_read (thriftpy/transport/framed/cyframed.c:1526)
  File "thriftpy/transport/framed/cyframed.pyx", line 68, in thriftpy.transport.framed.cyframed.TCyFramedTransport.read_frame (thriftpy/transport/framed/cyframed.c:1716)
  File "thriftpy/transport/framed/cyframed.pyx", line 31, in thriftpy.transport.framed.cyframed.TCyFramedTransport.read_trans (thriftpy/transport/framed/cyframed.c:1254)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
  File "/usr/local/lib/python2.7/dist-packages/thriftpy/transport/socket.py", line 125, in read
    message='TSocket read 0 bytes')
thriftpy.transport.TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)
```

sparse list works fine:
```
sparse list     
ssh tunnel to Nimbus s1.eu-west-1.compute.internal:6627 established.
No topologies found.
```
So this doesn't seem to be connectivity error

Is this sparse error? storm misconfiguration?

**Comment by SimSimY** [comment]
This appears to be due to misconfiguration of the nimbu server and had nothing to do with sparse.

**Comment by liorsbg** [comment]
@SimSimY I'm having the same issue, `sparse list` works, but I can't submit (`TTransportException(message='TSocket read 0 bytes', type=4)`). 

What was the misconfiguration? Where do you recommend to start debugging this?

**Comment by SimSimY** [comment]
In our case we had "two"(*) nimbus servers in the storm UI, one of them "dead" and one "active", we removed the "dead" server and managed to deploy

* It was the same server with two different  hostnames hence the misconfiguration

**Comment by mbande** [comment]
@SimSimY same issue here, like @liorsbg ```sparse list``` works, but i can't submit
in my case, there is a single "active" nimbus server

**Comment by aminalaee** [comment]
@SimSimY How did you remove the "dead" one? I always get an extra "dead" localhost nimbus and I'm not able to submit my topology.

**Comment by aminalaee** [comment]
I removed the *dead* nimbus, in the dataDir of zookeeper I deleted Snapshot files and restarted Zookeeper, Nimbus and Supervisor.
But still when submitting topology I get:
`thriftpy.transport.TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)`
