### ISSUE TITLE
RuntimeException: Anchored onto ... after ack/fail

### ISSUE THREAD

**Issue by mbande** [Parsely/streamparse#325]
running a topology locally, i get this from one of bolts:
```
...
errorString: 
java.lang.RuntimeException: Anchored onto -8438679503700935238 after ack/fail
	at org.apache.storm.task.ShellBolt.handleEmit(ShellBolt.java:212) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt.access$1300(ShellBolt.java:70) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:357) [storm-core-1.0.2.jar:1.0.2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
20702 [Thread-25] ERROR o.a.s.d.executor - 
java.lang.RuntimeException: Anchored onto -8438679503700935238 after ack/fail
	at org.apache.storm.task.ShellBolt.handleEmit(ShellBolt.java:212) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt.access$1300(ShellBolt.java:70) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:357) [storm-core-1.0.2.jar:1.0.2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```
in the mentioned bolt, i did:
```py
   ...
    def process(self, tup):
        ...
        if some_condition:
            self.fail(tup)

        self.emit([result, ])
```
changing last part to:
```py
        if some_condition:
            self.fail(tup)
        else:
            self.emit([entity, ])
```
i get:
```
...
java.lang.RuntimeException: Acked a non-existent or already acked/failed id: -8354207557294191959
	at org.apache.storm.task.ShellBolt.handleAck(ShellBolt.java:188) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt.access$900(ShellBolt.java:70) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:345) [storm-core-1.0.2.jar:1.0.2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
20636 [Thread-27] ERROR o.a.s.d.executor - 
java.lang.RuntimeException: Acked a non-existent or already acked/failed id: -8354207557294191959
	at org.apache.storm.task.ShellBolt.handleAck(ShellBolt.java:188) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt.access$900(ShellBolt.java:70) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:345) [storm-core-1.0.2.jar:1.0.2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

what is going on here?

**Comment by amontalenti** [comment]
Here's a hint that may help: make sure you turn off auto_ack & auto_fail if you are manually calling ack/fail. Otherwise there is a chance that the base Bolt class will attempt to ack/fail a tuple after you already have.

**Comment by mbande** [comment]
thank you @amontalenti

**Comment by liujiaqiid** [comment]
great helpful @amontalenti
