### ISSUE TITLE
python 3 error with component stats: TypeError: 'dict_values' object does not support indexing

### ISSUE THREAD

**Issue by mbande** [Parsely/streamparse#333]
traceback
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/streamparse/cli/stats.py", line 98, in _get_component_ui_detail
    return detail.values()[0]
TypeError: 'dict_values' object does not support indexing
```

**Comment by dan-blanchard** [comment]
Thanks for the report. Will fix this one right away.
