### ISSUE TITLE
Getting "Can't embed object in code ..." run time error during worker creation

### ISSUE THREAD

**Issue by victorpoluceno** [Parsely/streamparse#357]
I've build a very simple topology that implements a JVM Kafka Spout, very much like the Streamparse's example, with just a few minor changes. This topology works great on local mode (development) but fails on a real Storm cluster. After the topology is submitted, Storm try to create workers for this topology but fails with the following stack trace:

```
2017-02-09 12:46:28.776 b.s.d.worker [ERROR] Error on initialization of server mk-worker
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Can't embed object in code, maybe print-dup not defined: java.nio.HeapByteBuffer[pos=0 lim=14 cap=14], compiling:(NO_SOURCE_PATH:0:0)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler.analyze(Compiler.java:6445) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler.eval(Compiler.java:6700) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler.eval(Compiler.java:6666) ~[clojure-1.6.0.jar:?]
	at clojure.core$eval.invoke(core.clj:2927) ~[clojure-1.6.0.jar:?]
	at backtype.storm.thrift$instantiate_java_object.invoke(thrift.clj:38) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.daemon.task$get_task_object.invoke(task.clj:85) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.daemon.task$mk_task_data$fn__5375.invoke(task.clj:185) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.util$assoc_apply_self.invoke(util.clj:912) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.daemon.task$mk_task_data.invoke(task.clj:178) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.daemon.task$mk_task.invoke(task.clj:189) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.daemon.executor$mk_executor$fn__5575.invoke(executor.clj:352) ~[storm-core-0.10.2.jar:0.10.2]
	at clojure.core$map$fn__4245.invoke(core.clj:2557) ~[clojure-1.6.0.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.6.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.6.0.jar:?]
	at clojure.lang.RT.seq(RT.java:484) ~[clojure-1.6.0.jar:?]
	at clojure.core$seq.invoke(core.clj:133) ~[clojure-1.6.0.jar:?]
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~[clojure-1.6.0.jar:?]
	at clojure.core.protocols$fn__6078.invoke(protocols.clj:54) ~[clojure-1.6.0.jar:?]
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13) ~[clojure-1.6.0.jar:?]
	at clojure.core$reduce.invoke(core.clj:6289) ~[clojure-1.6.0.jar:?]
	at clojure.core$into.invoke(core.clj:6341) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.executor$mk_executor.invoke(executor.clj:352) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.daemon.worker$fn__7112$exec_fn__1236__auto__$reify__7114$iter__7119__7123$fn__7124.invoke(worker.clj:452) ~[storm-core-0.10.2.jar:0.10.2]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.6.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.6.0.jar:?]
	at clojure.lang.RT.next(RT.java:598) ~[clojure-1.6.0.jar:?]
	at clojure.core$next.invoke(core.clj:64) ~[clojure-1.6.0.jar:?]
	at clojure.core$dorun.invoke(core.clj:2856) ~[clojure-1.6.0.jar:?]
	at clojure.core$doall.invoke(core.clj:2871) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$fn__7112$exec_fn__1236__auto__$reify__7114.run(worker.clj:452) ~[storm-core-0.10.2.jar:0.10.2]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at javax.security.auth.Subject.doAs(Unknown Source) ~[?:1.8.0_121]
	at backtype.storm.daemon.worker$fn__7112$exec_fn__1236__auto____7113.invoke(worker.clj:426) ~[storm-core-0.10.2.jar:0.10.2]
	at clojure.lang.AFn.applyToHelper(AFn.java:178) ~[clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.6.0.jar:?]
	at clojure.core$apply.invoke(core.clj:624) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$fn__7112$mk_worker__7189.doInvoke(worker.clj:409) [storm-core-0.10.2.jar:0.10.2]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:542) [storm-core-0.10.2.jar:0.10.2]
	at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.10.2.jar:0.10.2]
Caused by: java.lang.RuntimeException: Can't embed object in code, maybe print-dup not defined: java.nio.HeapByteBuffer[pos=0 lim=14 cap=14]
	at clojure.lang.Util.runtimeException(Util.java:221) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler$ObjExpr.emitValue(Compiler.java:4664) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler$ObjExpr.emitConstants(Compiler.java:4703) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler$ObjExpr.compile(Compiler.java:4168) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3904) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642) ~[clojure-1.6.0.jar:?]
	... 43 more
```

I'm not sure if this has something to do with Streamparse or is just a Storm issue. I've done some debug and seems to happen when Clojure runs a eval to evaluate a Java object, probably my Java Spout, but I haven't be able to determine way it fails to evaluate it. Anyway, I'm running with:

```
Storm version: 0.10.2
Streamparse 3.4.0
Java JRE 1.8.0_121
```
Any help is much appreciated. Thanks a lot for great work with Streamparse!

**Comment by victorpoluceno** [comment]
After some testing I discovered that this error happens if my JVM Kafka Spout has a constructor expecting arguments. As far as I understand arguments should be passed to Java class constructor from the `args_list` argument of [JavaSpout](http://streamparse.readthedocs.io/en/stable/api.html#streamparse.JavaSpout.spec). But that results in the `Can't embed object in code` exception. So, I wondering if I missing something here or even if may be none as ever used a Java Spout with arguments in a real Storm cluster.

**Comment by dan-blanchard** [comment]
I haven't seen this exception before. Are you required to use Storm 0.10.2? It's possible this is something they've fixed since then.

Also, one thing to keep in mind is that your JVM Spout's constructor can only take basic data types, because that's all streamparse can translate Python data types into. So that's another potential source of issues.

**Comment by victorpoluceno** [comment]
Not exactly required but I'm moving from a setup of Pyleus/Storm 0.9x and I'm afraid of moving too many versions ahead during this initial migration, but I think I gonna give Storm 1.x a try.

BTW, I was using only basic data types. So, I think it may be a problem with Storm version as you said. Gonna test with Storm 1.x and report back here as soon as possible.

**Comment by bobgrigoryan** [comment]
had same problem today. (storm version 1.0.2, streamparse 3.4.0).
the topology was working fine on local cluster (with "sparse run"),
but was giving the error if submitted to remote server (with "sparse submit").
also was working fine with empty "arg_list".

after some testing found out that replacing:
`        args_list=[
            'dev',
        ],
`
with:
`        args_list=[
            u'dev',
        ],
`
seems to solve the problem.

also might be a problem with python version on remote server (2.7.6 vs local 2.7.12) or with encoding the args in thrift.

**Comment by dan-blanchard** [comment]
@bobgrigoryan, thank you! That is very valuable info.

**Comment by dan-blanchard** [comment]
Really this probably boils down to a documentation issue. You can see how we decide what data types to convert things to [here](https://github.com/Parsely/streamparse/blob/master/streamparse/dsl/util.py#L12-L31). It should be documented that you need to use unicode strings to pass string arguments to Java, because that's what Java expects them to be. If we did the conversion from bytes to unicode for you, we'd end up in a situation where people couldn't pass binary arguments to Java constructors if they wanted to.
