### ISSUE TITLE
 No module named streamparse.run ?

### ISSUE THREAD

**Issue by BreakTom** [Parsely/streamparse#377]
from streamparse.run import main
ImportError: No module named streamparse.run

	at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) ~[storm-core-1.1.0.jar:1.1.0]
	at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) ~[storm-core-1.1.0.jar:1.1.0]
	at org.apache.storm.daemon.executor$fn__5044$fn__5057.invoke(executor.clj:791) ~[storm-core-1.1.0.jar:1.1.0]
	at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) [storm-core-1.1.0.jar:1.1.0]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Fatal error: local() encountered an error (return code 1) while executing 'storm jar /Users/liu/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /var/folders/rw/v_d8ch7148ldsjlny5dk7x640000gn/T/tmpk7JtbI.yaml'

Aborting.

why?

**Comment by dan-blanchard** [comment]
I need a lot more information to be helpful:

- Python version
- streamparse version
- command you ran
- storm version

**Comment by BreakTom** [comment]
sorry,I have solved the problem, I pip install  streamparse in virtualenv,I don't know what's wrong.environment variable?

**Comment by dan-blanchard** [comment]
If streamparse wasn't install in your virtualenv, that error would be expected.
