### ISSUE TITLE
channel 2: open failed: administratively prohibited: open failed

### ISSUE THREAD

**Issue by ProgSys** [Parsely/streamparse#384]
Hi,

I am new to streamparse and I am trying to setup a local cluster by following the Quickstart guide.
But when I try to use `sparse submit` and enter the password, I get this error:

```
storm@192.168.178.53's password: 
ssh tunnel to Nimbus 192.168.178.53:6627 established.
channel 2: open failed: administratively prohibited: open failed
```
Full log:
```
> sparse submit
[192.168.178.53] Executing task '_create_or_update_virtualenv'
[192.168.178.35] Executing task '_create_or_update_virtualenv'
[192.168.178.53] Uploading virtualenvs/scoretweets.txt to temporary file.
[192.168.178.53] run: mktemp /tmp/streamparse_requirements-XXXXXXXXX.txt
[192.168.178.53] out: /tmp/streamparse_requirements-Pvh7XKU5L.txt
[192.168.178.53] out: 

[192.168.178.53] put: virtualenvs/scoretweets.txt -> /tmp/streamparse_requirements-Pvh7XKU5L.txt
[192.168.178.53] Updating virtualenv: scoretweets
[192.168.178.53] run: pip install --upgrade 'pip~=9.0'
[192.168.178.53] out: Requirement already up-to-date: pip~=9.0 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages
[192.168.178.53] out: 

[192.168.178.53] run: pip install -r /tmp/streamparse_requirements-Pvh7XKU5L.txt --exists-action w --upgrade --upgrade-strategy only-if-needed
[192.168.178.35] Uploading virtualenvs/scoretweets.txt to temporary file.
[192.168.178.35] run: mktemp /tmp/streamparse_requirements-XXXXXXXXX.txt
[192.168.178.53] out: Requirement already up-to-date: streamparse in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from -r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.35] out: /tmp/streamparse_requirements-U9yhPYS7C.txt
[192.168.178.35] out: 

[192.168.178.35] put: virtualenvs/scoretweets.txt -> /tmp/streamparse_requirements-U9yhPYS7C.txt
[192.168.178.35] Updating virtualenv: scoretweets
[192.168.178.35] run: pip install --upgrade 'pip~=9.0'
[192.168.178.53] out: Requirement already up-to-date: pymongo in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from -r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 2))
[192.168.178.53] out: Requirement not upgraded as not directly required: thriftpy>=0.3.2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: pystorm>=3.1.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: ruamel.yaml in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: requests in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: prettytable in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: six>=1.5 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: jinja2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: fabric3 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: simplejson in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: ply<4.0,>=3.4 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from thriftpy>=0.3.2->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: msgpack-python in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from pystorm>=3.1.1->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: contextlib2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from pystorm>=3.1.1->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from ruamel.yaml->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: idna<2.6,>=2.5 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: urllib3<1.22,>=1.21.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: certifi>=2017.4.17 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: MarkupSafe>=0.23 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from jinja2->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: paramiko<3.0,>=2.0 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: pynacl>=1.0.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: pyasn1>=0.1.7 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: cryptography>=1.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: bcrypt>=3.1.3 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: cffi>=1.4.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from pynacl>=1.0.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: asn1crypto>=0.21.0 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: ipaddress in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: enum34 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: Requirement not upgraded as not directly required: pycparser in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-Pvh7XKU5L.txt (line 1))
[192.168.178.53] out: 

[192.168.178.53] run: rm /tmp/streamparse_requirements-Pvh7XKU5L.txt
[192.168.178.35] out: Requirement already up-to-date: pip~=9.0 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages
[192.168.178.35] out: 

[192.168.178.35] run: pip install -r /tmp/streamparse_requirements-U9yhPYS7C.txt --exists-action w --upgrade --upgrade-strategy only-if-needed
[192.168.178.35] out: Requirement already up-to-date: streamparse in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from -r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement already up-to-date: pymongo in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from -r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 2))
[192.168.178.35] out: Requirement not upgraded as not directly required: fabric3 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: simplejson in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: six>=1.5 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: pystorm>=3.1.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: ruamel.yaml in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: requests in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: jinja2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: prettytable in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: thriftpy>=0.3.2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: paramiko<3.0,>=2.0 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: contextlib2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from pystorm>=3.1.1->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: msgpack-python in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from pystorm>=3.1.1->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: ruamel.ordereddict in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from ruamel.yaml->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: certifi>=2017.4.17 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: urllib3<1.22,>=1.21.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: idna<2.6,>=2.5 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from requests->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: MarkupSafe>=0.23 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from jinja2->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: ply<4.0,>=3.4 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from thriftpy>=0.3.2->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: cryptography>=1.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: bcrypt>=3.1.3 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: pyasn1>=0.1.7 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: pynacl>=1.0.1 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: asn1crypto>=0.21.0 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: enum34 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: ipaddress in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: cffi>=1.7 in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: Requirement not upgraded as not directly required: pycparser in ./data/virtualenvs/scoretweets/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.1->paramiko<3.0,>=2.0->fabric3->streamparse->-r /tmp/streamparse_requirements-U9yhPYS7C.txt (line 1))
[192.168.178.35] out: 

[192.168.178.35] run: rm /tmp/streamparse_requirements-U9yhPYS7C.txt
Cleaning from prior builds...
Creating topology JAR...
JAR created: /home/progsys/Apache/big_data/storm/_build/scoretweets-0.0.1.jar
Removing _resources temporary directory...done
Deploying "scoretweets" topology...
storm@192.168.178.53's password: 
ssh tunnel to Nimbus 192.168.178.53:6627 established.
channel 2: open failed: administratively prohibited: open failed
Traceback (most recent call last):
  File "/home/progsys/miniconda3/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/home/progsys/miniconda3/lib/python3.6/site-packages/streamparse/cli/sparse.py", line 79, in main
    args.func(args)
  File "/home/progsys/miniconda3/lib/python3.6/site-packages/streamparse/cli/submit.py", line 276, in main
    timeout=args.timeout)
  File "/home/progsys/miniconda3/lib/python3.6/site-packages/streamparse/cli/submit.py", line 221, in submit_topology
    remote_jar_path = _upload_jar(nimbus_client, local_jar_path)
  File "/home/progsys/miniconda3/lib/python3.6/site-packages/streamparse/cli/submit.py", line 114, in _upload_jar
    upload_location = nimbus_client.beginFileUpload()
  File "/home/progsys/miniconda3/lib/python3.6/site-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/home/progsys/miniconda3/lib/python3.6/site-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6325)
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1546)
  File "thriftpy/transport/framed/cyframed.pyx", line 48, in thriftpy.transport.framed.cyframed.TCyFramedTransport.c_read (thriftpy/transport/framed/cyframed.c:1526)
  File "thriftpy/transport/framed/cyframed.pyx", line 68, in thriftpy.transport.framed.cyframed.TCyFramedTransport.read_frame (thriftpy/transport/framed/cyframed.c:1716)
  File "thriftpy/transport/framed/cyframed.pyx", line 31, in thriftpy.transport.framed.cyframed.TCyFramedTransport.read_trans (thriftpy/transport/framed/cyframed.c:1254)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
  File "/home/progsys/miniconda3/lib/python3.6/site-packages/thriftpy/transport/socket.py", line 125, in read
    message='TSocket read 0 bytes')
thriftpy.transport.TTransportException: TTransportException(type=4, message='TSocket read 0 bytes')

```

This is my config file:
```
{
    "serializer": "json",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "storm",
            "ssh_password": "storm",
            "nimbus": "192.168.178.53",
            "workers": [
		"192.168.178.53",
		"192.168.178.35"
		],
            "log": {
                "path": "/var/storm",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "info"
            },
	    "use_ssh_for_nimbus": true,
            "virtualenv_root": "data/virtualenvs"
        }
    }
}
```
It seams to do something with the ssh connection.
Looking online I found this thread: https://unix.stackexchange.com/questions/14160/ssh-tunneling-error-channel-1-open-failed-administratively-prohibited-open , but none of there instructions seam to help.
My `/etc/ssh/sshd_config` seams to be correct and `/etc/hosts` has a local host entry: 
```
127.0.0.1	localhost
```

Any idears what the problem could be?
Thanks for any help in advance!

**Comment by iiAnderson** [comment]
Did you find a fix to this? I'm done almost exactly what you've done (except I get  the error `channel 2: open failed: connect failed: Connection refused`). I've also tried deploying the nimbus locally (i.e. turn off use_ssh_for_nimbus) and it still fails with the same error.

**Comment by Sstrap** [comment]
I am also new to streamparse and try to make storm UI run in local but get stuck with the same error as you. Does anyone find a solution to this issue?

**Comment by liyandi** [comment]
I had a similar issue with the error `channel 2: open failed: connect failed`, followed by some thrift open error. In my case, I discovered two causes. 
1. zookeeper/nimbus down. In this case, errors also shows up in storm UI;
2. wrong nimbus port in `config.json`. I typed `netstat -al` on the leader machine to find out that the port is not 6627 but 6629. So I changed the nimbus hosts to `XX.XX.XX.XX:6629` but kept the workers' port untouched, like `["XX.XX.XX.XX"]`, then everything worked.
Hope it helps.
