### ISSUE TITLE
invalid topology name

### ISSUE THREAD

**Issue by NoahLiot** [Parsely/streamparse#424]
```Traceback (most recent call last):
  File "/Users/xxxx/anaconda3/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/streamparse/cli/sparse.py", line 79, in main
    args.func(args)
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/streamparse/cli/submit.py", line 299, in main
    user=args.user)
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/streamparse/cli/submit.py", line 239, in submit_topology
    env_config, nimbus_client, options=options)
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/streamparse/cli/submit.py", line 89, in _submit_topology
    'Storm topology.'.format(topology_name))
ValueError: Nimbus says darwinnews is an invalid name for a Storm topology.```

**Comment by dume2007** [comment]
I think the name `darwinnews` is already existed. 
You should kill the old topology task before submit.

**Comment by NoahLiot** [comment]
It was killed. I was able to workaround by removing the check, which for some reason is related to version used (The check only takes place is your version is higher than...)
Since the check has been removed everything is working and I am actually using this topology name. 
Not sure what is going on there.

**Comment by dan-blanchard** [comment]
That is bizarre. What versions of Storm and streamparse were you using?
