### ISSUE TITLE
Sparse just get stuck in the creation of the Uber-JAR.

### ISSUE THREAD

**Issue by NoahLiot** [Parsely/streamparse#431]
This is what I ran:
`sparse run -d -n mytopology`

And this where it gets stuck:

`Cleaning from prior builds...`
`Creating topology Uber-JAR...`

It used to work, and I upgraded a lot of packages using pip. It is working on another environment too. Did I introduce some incompatibilities?

I am running:

`Leiningen 2.8.1 on Java 1.8.0_162 Java HotSpot(TM) 64-Bit Server VM`

`Running: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/usr/local/opt/stormzookeeper/apache-storm-1.2.1 -Dstorm.log.dir=/usr/local/opt/stormzookeeper/apache-storm-1.2.1/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /usr/local/opt/stormzookeeper/apache-storm-1.2.1/*:/usr/local/opt/stormzookeeper/apache-storm-1.2.1/lib/*:/usr/local/opt/stormzookeeper/apache-storm-1.2.1/extlib/*:/usr/local/opt/stormzookeeper/apache-storm-1.2.1/extlib-daemon/*:/usr/local/opt/stormzookeeper/apache-storm-1.2.1/conf org.apache.storm.utils.VersionInfo
Storm 1.2.1`

`sparse 3.13.1`

When I interrupt the spin, I always get:

```Traceback (most recent call last):
  File "/Users/user/anaconda3/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/Users/user/anaconda3/lib/python3.6/site-packages/streamparse/cli/sparse.py", line 79, in main
    args.func(args)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/streamparse/cli/run.py", line 103, in main
    env_name=args.environment, config_file=args.config)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/streamparse/cli/run.py", line 54, in run_local_topology
    topology_jar = jar_for_deploy(simple_jar=False)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/streamparse/cli/jar.py", line 34, in jar_for_deploy
    res = local(cmd, capture=True)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/fabric/operations.py", line 1229, in local
    (stdout, stderr) = p.communicate()
  File "/Users/user/anaconda3/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Users/user/anaconda3/lib/python3.6/subprocess.py", line 1514, in _communicate
    ready = selector.select(timeout)
  File "/Users/user/anaconda3/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)```

I know it is very few, but if you tell me what you need to understand what is going on, I will provide it.

Cheers!

**Comment by NoahLiot** [comment]
I found, the issue. I had a hidden file in resource which was 13Gb, hence causing the JAR creation to take forever. Problem solved. Apologise for that.
