### ISSUE TITLE
sparse submit error  thriftpy2.thrift.TApplicationException: Internal error processing beginFileUpload

### ISSUE THREAD

**Issue by farons** [Parsely/streamparse#488]
* python 3.6.13
* strampase 4
* arm
* strom 2.2.0

Deploying "test_topology" topology. 
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/streamparse/cli/sparse.py", line 85, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/streamparse/cli/submit.py", line 386, in main
    active=args.active,
  File "/usr/local/lib/python3.6/site-packages/streamparse/cli/submit.py", line 290, in submit_topology
    remote_jar_path = _upload_jar(nimbus_client, local_jar_path)
  File "/usr/local/lib/python3.6/site-packages/streamparse/cli/submit.py", line 157, in _upload_jar
    upload_location = nimbus_client.beginFileUpload()
  File "/usr/local/lib/python3.6/site-packages/thriftpy2/thrift.py", line 219, in _req
    return self._recv(_api)
  File "/usr/local/lib/python3.6/site-packages/thriftpy2/thrift.py", line 236, in _recv
    raise x
thriftpy2.thrift.TApplicationException: Internal error processing beginFileUpload

**Comment by kbourgoin** [comment]
Cleaning out old issues. Please reopen if this is still an issue.
