### ISSUE TITLE
Topology Name Collision Reporting Sucks

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/streamparse#62]
If I try to deploy to a cluster and there's a topology running with the same name, streamparse throws an error. This is the correct behavior, but the error that's reported is a pain to sift through to figure out what just happened:

```
Traceback (most recent call last):
  File "/data/vRouting Python logging to /opt/storm/current/logs.
irtualenvs/storm/bin/sparse", line 9, in <module>
 Running lein command to submit topology to nimbus:
   load_entry_point('streamparse==0.0.13', 'console_scripts', 'sparse')()
  File "/home/kfb/src/ct/streamparse/streamparse/cmdln.py", line 93, in main
    args["--force"], args["--debug"])
  File "/data/virtualenvs/storm/local/lib/python2.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/home/kfb/src/ct/streamparse/streamparse/ext/invoke.py", line 272, in submit_topology
    run(full_cmd)
  File "/data/virtualenvs/storm/local/lib/pytholein run -m streamparse.commands.submit_topology/-main topologies/visits-prod.clj --option 'topology.workers=8' --option 'topology.acker.executors=8' --option 'topology.python.path="/data/virtualenvs/visits-prod/bin/python"' --option 'streamparse.log.path="/opt/storm/current/logs"' --option 'streamparse.log.level="info"' --option topology.max.spout.pending=1500 --option topology.message.timeout.secs=300 --option supervisor.worker.timeout.secs=300 --option 'parsely.deployment_stage="prod"'
n2.7/site-packages/invoke/runner.py", line 160, in run
    raise Failure(result)
invoke.exceptions.Failure: Command execution failure!

Exit code: 1

Stderr:

Exception in thread "main" java.lang.NullPointerException
	at streamparse.commands.submit_topology$submit_topology_BANG_.invoke(submit_topology.clj:27)
	at streamparse.commands.submit_topology$_main.doInvoke(submit_topology.clj:{:option {parsely.deployment_stage prod, supervisor.worker.timeout.secs 300, topology.message.timeout.secs 300, topology.max.spout.pending 1500, streamparse.log.level info, streamparse.log.path /opt/storm/current/logs, topology.python.path /data/virtualenvs/visits-prod/bin/python, topology.acker.executors 8, topology.workers 8}, :debug false, :port 6627, :host localhost, :help false}
74)
	at clojure.lang.RestFn.invoke(RestFn.java:3204)
	at clojure.lang.VaCaught exception: Topology with name `visits` already exists on cluster
r
.invoke(Var.java:510)
	at user$eval5.invoke(form-init5814132293844863193.clj:1)
	ajava.lang.RuntimeException: Topology with name `visits` already exists on cluster
t clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler. at backtype.storm.StormSubmitter.submitTopology (StormSubmitter.java:102)
eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064    backtype.storm.StormSubmitter.submitTopology (StormSubmitter.java:70)
)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(ma    streamparse.commands.submit_topology$submit_topology_BANG_.invoke (submit_topology.clj:22)
in.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initi    streamparse.commands.submit_topology$_main.doInvoke (submit_topology.clj:74)
alize.invoke(main.clj:327)
	at clojure.main$null_o    clojure.lang.RestFn.invoke (RestFn.java:3204)
pt.invoke(main.clj:362)
	at clojure.main$ma    clojure.lang.Var.invoke (Var.java:510)
in.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(Re    user$eval5.invoke (form-init5814132293844863193.clj:1)
stFn.java:421)
	at clojure.lang.Var.invoke(Var.java:    clojure.lang.Compiler.eval (Compiler.java:6619)
419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163    clojure.lang.Compiler.eval (Compiler.java:6609)
)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clo    clojure.lang.Compiler.load (Compiler.java:7064)
jure.main.main(main.java:37)



    clojure.lang.Compiler.loadFile (Compiler.java:7020)
    clojure.main$load_script.invoke (main.clj:294)
    clojure.main$init_opt.invoke (main.clj:299)
    clojure.main$initialize.invoke (main.clj:327)
    clojure.main$null_opt.invoke (main.clj:362)
    clojure.main$main.doInvoke (main.clj:440)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:419)
    clojure.lang.AFn.applyToHelper (AFn.java:163)
    clojure.lang.Var.applyTo (Var.java:532)
    clojure.main.main (main.java:37)
```

**Comment by jasonrhaas** [comment]
at clojure.lang.VaCaught exception: **Topology with name `visits` already exists on cluster**
There it is!  It's kind of like playing "Where's Waldo" but with error messages.

+1 for any improved legibility to error handling.

**Comment by amontalenti** [comment]
Yea, it's a Java affliction, leakily flowing through the abstraction :)

We have some new code that does a "force" submit (-f) and that, as a result, queries for the topology before trying to submit it. This should be an easy fix.

**Comment by dan-blanchard** [comment]
This has been fixed for a while.
